repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8  # Use the latest tag from https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
      - id: ruff-format
